### ISSUE TITLE
カスタムユニットでコードを作成後、出力用ソースのタブをクリックすると何も表示されません。

### ISSUE THREAD

**Issue by Raphael-D** [appleple/custom-field-maker#1]
いつもお世話になっております。
清水です。

カスタムユニットでコードを作成後、出力用ソースのタブをクリックすると全面真っ白な画面になります。

ご参考になれば幸いかと思い、当方の環境をお伝えいたします。
・ブラウザ：Chrome Version 63.0.3239.132 (Official Build) (64-bit)
・OS：macOS High Sierra Version 10.13.2

カスタムユニットで作成したコード
・画像のフォーム２箇所
・テキストエリア

入力用ソースのコード
`
<table class="acms-admin-table-admin-edit">
  <tr>
    <th>画像の説明文
      <i class="acms-admin-icon-tooltip js-acms-tooltip" data-acms-tooltip="画像の説明文を入力してください。"></i>
    </th>
    <td>
      <textarea name="custom_dual_img_desc{id}" class="acms-admin-form-width-full">{custom_dual_img_desc}</textarea>
      <input type="hidden" name="unit{id}[]" value="custom_dual_img_desc{id}">
    </td>
  </tr>
  <tr>
    <th>左側画像
      <i class="acms-admin-icon-tooltip js-acms-tooltip" data-acms-tooltip="左側に表示する画像をアップロードしてください。"></i>
    </th>
    <td class="js-img_resice_cf">
      
      <img src="%{ARCHIVES_DIR}{custom_dual_img_left@path}" class="acms-admin-img-responsive js-img_resize_preview">
      <input type="hidden" name="custom_dual_img_left{id}@old" value="{custom_dual_img_left@path}">
      <div class="acms-admin-form-checkbox">
        <input type="checkbox" name="custom_dual_img_left{id}@edit" value="delete" id="input-checkbox-custom_dual_img_left@edit">
        <label for="input-checkbox-custom_dual_img_left@edit">
          <i class="acms-admin-ico-checkbox"></i>削除</label>
      </div>
      
      <img src="%{ARCHIVES_DIR}{custom_dual_img_left@path}" class="acms-admin-img-responsive js-img_resize_preview" style="display: none;">
      
      <input type="file" name="custom_dual_img_left" size="20" class="js-img_resize_input">
      <br>
      <input type="hidden" name="unit{id}[]" value="custom_dual_img_left">
      <input type="hidden" name="custom_dual_img_left{id}:extension" value="image">
      <input type="hidden" name="custom_dual_img_left{id}@filename" value="">
    </td>
  </tr>
  <tr>
    <th>右側画像
      <i class="acms-admin-icon-tooltip js-acms-tooltip" data-acms-tooltip="右側に表示する画像をアップロードしてください。"></i>
    </th>
    <td class="js-img_resice_cf">
      
      <img src="%{ARCHIVES_DIR}{custom_dual_img_right@path}" class="acms-admin-img-responsive js-img_resize_preview">
      <input type="hidden" name="custom_dual_img_right{id}@old" value="{custom_dual_img_right@path}">
      <div class="acms-admin-form-checkbox">
        <input type="checkbox" name="custom_dual_img_right{id}@edit" value="delete" id="input-checkbox-custom_dual_img_right@edit">
        <label for="input-checkbox-custom_dual_img_right@edit">
          <i class="acms-admin-ico-checkbox"></i>削除</label>
      </div>
      
      <img src="%{ARCHIVES_DIR}{custom_dual_img_right@path}" class="acms-admin-img-responsive js-img_resize_preview" style="display: none;">
      
      <input type="file" name="custom_dual_img_right" size="20" class="js-img_resize_input">
      <br>
      <input type="hidden" name="unit{id}[]" value="custom_dual_img_right">
      <input type="hidden" name="custom_dual_img_right{id}:extension" value="image">
      <input type="hidden" name="custom_dual_img_right{id}@filename" value="">
    </td>
  </tr>
</table>
`

コンソールには以下のエラーが出ておりました。
`bundle.js:11 ReferenceError: src is not defined
    at bundle.js:57
    at Array.map (<anonymous>)
    at t.value (bundle.js:57)
    at l (bundle.js:11)
    at beginWork (bundle.js:11)
    at r (bundle.js:11)
    at o (bundle.js:11)
    at s (bundle.js:11)
    at y (bundle.js:11)
    at E (bundle.js:11)
l @ bundle.js:11
s @ bundle.js:11
y @ bundle.js:11
E @ bundle.js:11
batchedUpdates @ bundle.js:11
J @ bundle.js:11
ke @ bundle.js:11
`

`
bundle.js:57 Uncaught ReferenceError: src is not defined
    at bundle.js:57
    at Array.map (<anonymous>)
    at t.value (bundle.js:57)
    at l (bundle.js:11)
    at beginWork (bundle.js:11)
    at r (bundle.js:11)
    at o (bundle.js:11)
    at s (bundle.js:11)
    at y (bundle.js:11)
    at E (bundle.js:11)`

よろしくお願いいたします。

**Comment by steelydylan** [comment]
ありがとうございます。先ほどバグを修正したので、ブラウザのキャッシュを消していただくとエラーが出なくなるはずです。よろしくお願いします。
https://github.com/appleple/custom-field-maker/commit/74858a2047a2a17db07f83b06f08752c1ed21860

**Comment by Raphael-D** [comment]
確認いたしました。
迅速な対応ありがとうございます！
とても便利なツールなのでいつも助かっております。

**Comment by steelydylan** [comment]
いえいえ。こちらこそバグ報告ありがとうございました。
また何かあればご報告していただけると幸いです。
