### ISSUE TITLE
カスタムフィールドの画像で@pathが出力されない

### ISSUE THREAD

**Issue by yokozunat** [appleple/custom-field-maker#3]
`<img src="%{ARCHIVES_DIR}{hoge@}" class="acms-admin-img-responsive js-img_resize_preview">
`
カスタムフィールドの画像の入力用ソースですが、上記のように、pathがない形で出力されていました。
https://developer.a-blogcms.jp/tools/

**Comment by steelydylan** [comment]
こちらでみたところ、@path出力されてました。
